# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-30 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0002_auto_20180430_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['customer_name'], 'verbose_name': '\u65e5\u62a5', 'verbose_name_plural': '\u65e5\u62a5'},
        ),
    ]
