# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-30 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0006_auto_20180524_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='date',
            field=models.DateField(),
        ),
    ]
