# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-17 02:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one', '0011_auto_20180601_0826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-date', 'author'], 'verbose_name': '\u65e5\u62a5', 'verbose_name_plural': '\u65e5\u62a5'},
        ),
    ]
